version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=production
    volumes:
      - ./rails-api:/rails-api
